### ISSUE TITLE
Two parellel `run` produce pg error "Connection terminated unexpectedl"

### ISSUE THREAD

**Issue by madeindjs** [graphile/worker#149]
### Summary

I wanted to make two `run()` call in parallel with `Promise.all` but I get a Postgres error randomly on production environment.

### Steps to reproduce

I wanted to open two parallel worker with different tasks

1. With given config

~~~js
{
  connectionString,
  concurrency: 1,
  noHandleSignals: false,
  pollInterval: 1000,
  taskList: {
    fetchDailyPageTask,
    fetchDailyQueryTask,
    fetchDailyQueryPageTask,
  },
  logger: new JobLogger(logFactory),
}
~~~

2. with given config

~~~js
{
  connectionString,
  concurrency: 5,
  noHandleSignals: false,
  taskList: {
    helloTask,
    computeDailyPageTask,
    computeDailyQueryTask,
    computeDailyQueryPageTask,
    addUserSitesTask,
    fetchGoogleCredentialsTask,
  },
  logger: new JobLogger(logFactory),
}
~~~

So to be able to do that, I decided to use `Promise.all`to run both `run` in parrallel like this :

~~~ts
function main() {
  return Promise.all([
    run({/* config 1 */}, logger: new JobLogger(logFactory), }),
    run({/* config 2 */}, logger: new JobLogger(logFactory), }),
  ]);
}

main.catch(console.error)
~~~

### Expected results

Get both promises work together.

### Actual results

I get some `pg` error on random time.

* error on backend side

~~~
Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (events.js:420:28)
    at Connection.emit (events.js:314:20)
    at Connection.EventEmitter.emit (domain.js:486:12)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:102:12)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
~~~

* error on postgres log

~~~
2020-11-03 07:59:13.007 UTC [9601] db@server FATAL:  canceling authentication due to timeout
2020-11-03 07:59:13.010 UTC [9602] db@server FATAL:  canceling authentication due to timeout
2020-11-03 07:59:53.108 UTC [9600] db@server LOG:  could not receive data from client: Connection reset by peer
2020-11-03 07:59:53.110 UTC [9599] db@server LOG:  could not receive data from client: Connection reset by peer
2020-11-03 07:59:53.112 UTC [9598] db@server LOG:  could not receive data from client: Connection reset by peer
~~~

### Additional context

* Postgres 12.3
* Node 14.7
* graphile-worker 0.8.1

**Comment by benjie** [comment]
Attempted to reproduce:

```ts
# demo.ts
import { run, RunnerOptions } from "graphile-worker";

function config(nr: number): RunnerOptions {
  return {
    connectionString: "graphile_worker",
    taskList:
      nr === 1
        ? {
            log1(payload) {
              console.log("LOG1", payload);
            },
          }
        : nr === 2
        ? {
            log2(payload) {
              console.log("LOG2", payload);
            },
          }
        : {},
  };
}

async function main() {
  const [worker1, worker2] = await Promise.all([
    run(config(1)),
    run(config(2)),
  ]);
  await Promise.all([worker1.promise, worker2.promise]);
}

main().catch(console.error);
```

psql:

```
[graphile_worker] # select add_job('log1', '{"hi":1}'), add_job('log2', '{"hello2":2}');
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│                                                                   add_job                                                   
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ (23314233,,log1,"{""hi"":1}",0,"2020-11-04 09:42:51.560743+00",0,25,,"2020-11-04 09:42:51.560743+00","2020-11-04 09:42:51.56
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
(1 row)
Time: 10.625 ms
```

Terminal output:

```
$ yarn ts-node demo.ts                                                                                                                                                                                                
yarn run v1.22.5
$ /home/benjie/Dev/graphile/worker/node_modules/.bin/ts-node demo.ts
[core] INFO: Worker connected and looking for jobs... (task names: 'log2')
[core] INFO: Worker connected and looking for jobs... (task names: 'log1')
LOG2 { hello2: 2 }
[worker(worker-1c9a8e5255909952a3)] INFO: Completed task 23314234 (log2) with success (0.61ms)
LOG1 { hi: 1 }
[worker(worker-b23568c0f7f1420579)] INFO: Completed task 23314233 (log1) with success (0.18ms)
```

Does your PostgreSQL log have any hints?

**Comment by madeindjs** [comment]
I tried to reproduce with this code:

~~~ts
require('dotenv').config();

import {Helpers, Logger as JobLogger, makeWorkerUtils, run, runMigrations} from 'graphile-worker';
import {PoolClient} from 'pg';
import {env} from 'process';

const connectionString = `${env.TYPEORM_CONNECTION}://${env.TYPEORM_USERNAME}:${env.TYPEORM_PASSWORD}@${env.TYPEORM_HOST}/${env.TYPEORM_DATABASE}`;

async function countOpenedConnections(client: PoolClient) {
  const results = await client.query('SELECT sum(numbackends) as cnt FROM pg_stat_database');
  const count = results.rows[0].cnt;
  console.log(`${new Date().toISOString()} - debug - opened connections: ${count}`);
}

const task1 = async (payload: any, helpers: Helpers): Promise<void> => {
  await helpers.withPgClient(countOpenedConnections);
};
const task2 = async (payload: any, helpers: Helpers): Promise<void> => {
  await helpers.withPgClient(countOpenedConnections);
};

function logFactory(_scope) {
  return (level, message, meta) => {
    console.log(`${new Date().toISOString()} - ${level} - ${message}`);
  };
}

async function startWorkers() {
  await runMigrations({connectionString});
  return Promise.all([
    run({
      connectionString,
      concurrency: 2,
      noHandleSignals: false,
      pollInterval: 1000,
      taskList: {task1},
      logger: new JobLogger(logFactory),
    }),
    run({
      connectionString,
      concurrency: 3,
      noHandleSignals: false,
      pollInterval: 1000,
      taskList: {task2},
      logger: new JobLogger(logFactory),
    }),
  ]);
}

function logAddJobError(e: Error) {
  console.log(`${new Date().toISOString()} - error - Error during insert job ${JSON.stringify(e)}`);
}

async function main() {
  await startWorkers();

  const workerUtils = await makeWorkerUtils({connectionString});

  setInterval(() => workerUtils.addJob('task1', {}).catch(logAddJobError), 100);
  setInterval(() => workerUtils.addJob('task2', {}).catch(logAddJobError), 200);
}

main().catch(console.error);
~~~

After 4 minutes I had this error from log

~~~
2020-11-10T13:27:01.506Z - debug - Found task 335168 (task1)
2020-11-10T13:27:01.510Z - debug - opened connections: 73
2020-11-10T13:27:01.510Z - info - Completed task 335168 (task1) with success (4.43ms)
2020-11-10T13:27:01.885Z - debug - Found task 335224 (task1)
2020-11-10T13:27:01.888Z - debug - opened connections: 73
2020-11-10T13:27:01.888Z - info - Completed task 335224 (task1) with success (2.95ms)
2020-11-10T13:27:02.548Z - error - Error during insert job {"length":85,"name":"error","severity":"FATAL","code":"53300","file":"proc.c","line":"363","routine":"InitProcess"}
2020-11-10T13:27:02.648Z - error - Error during insert job {"length":85,"name":"error","severity":"FATAL","code":"53300","file":"proc.c","line":"363","routine":"InitProcess"}
2020-11-10T13:27:02.748Z - error - Error during insert job {"length":85,"name":"error","severity":"FATAL","code":"53300","file":"proc.c","line":"363","routine":"InitProcess"}
2020-11-10T13:27:02.807Z - error - Error during insert job {"length":85,"name":"error","severity":"FATAL","code":"53300","file":"proc.c","line":"363","routine":"InitProcess"}
2020-11-10T13:27:02.849Z - error - Error during insert job {"length":85,"name":"error","severity":"FATAL","code":"53300","file":"proc.c","line":"363","routine":"InitProcess"}
2020-11-10T13:27:02.948Z - error - Error during insert job {"length":85,"name":"error","severity":"FATAL","code":"53300","file":"proc.c","line":"363","routine":"InitProcess"}
2020-11-10T13:27:04.707Z - debug - Found task 335327 (task1)
2020-11-10T13:27:04.709Z - debug - opened connections: 100
2020-11-10T13:27:04.709Z - info - Completed task 335327 (task1) with success (1.43ms)
2020-11-10T13:27:04.751Z - error - Error during insert job {"length":85,"name":"error","severity":"FATAL","code":"53300","file":"proc.c","line":"363","routine":"InitProcess"}
2020-11-10T13:27:04.809Z - error - Error during insert job {"length":85,"name":"error","severity":"FATAL","code":"53300","file":"proc.c","line":"363","routine":"InitProcess"}
2020-11-10T13:27:04.852Z - error - Error during insert job {"length":85,"name":"error","severity":"FATAL","code":"53300","file":"proc.c","line":"363","routine":"InitProcess"}
~~~

During 3 minutes I had ~70 opened connections to Postgres but at a random time, connections bump to 100 opened connections without reasons (which is the default maximum for Postgres configuration).

**Comment by madeindjs** [comment]
Also I ran the same script with only one `run` (see bellow) during 20 minutes and I don't have any problem.

~~~ts
async function startWorkers() {
  await runMigrations({connectionString});
  return run({
    connectionString,
    concurrency: 5,
    noHandleSignals: false,
    pollInterval: 1000,
    taskList: {task1, task2},
    logger: new JobLogger(logFactory),
  });
}
~~~

**Comment by benjie** [comment]
Do you have other things connecting to your database? It feels like this isn't Graphile Worker's fault.

**Comment by madeindjs** [comment]
You're right. I tried to re-run the same script during some times and I cannot reproduce error... I close it for now. Thanks you for your help.
