### ISSUE TITLE
Question: Why worker failed if the job failed instead of waiting for new jobs?

### ISSUE THREAD

**Issue by natrayanp** [graphile/worker#165]
My understanding on the runner is if a particular job fails it will continue to process next job.
I tried Quickstart: library code in nestjs service (given the code below) and used "taskDirectory" instead of taskList.

2 Scenarios i checked:

Scenario 1:
Step 1: select * from graphile_worker.jobs; --> No pending jobs
Step 2: Moved out hello.js under task folder (task/hello.js).
Step 3: started the runner (Quickstart: Library code).  This inserted job with task_identifier = hello.

My expectation was that the runner will skip the job and will continue to watch for any new jobs

However, the process exited with the below error.

```
[core] INFO: Worker connected and looking for jobs... (task names: '')
/node_modules/graphile-worker/dist/worker.js:86
                    promise.reject(new Error(`Failed ${contiguousErrors} times in a row to acquire job; latest error: ${err.message}`));
                                   ^

Error: Failed 10 times in a row to acquire job; latest error: No runnable tasks!
    at doNext (/node_modules/graphile-worker/dist/worker.js:86:36)
    at Timeout.<anonymous> (/node_modules/graphile-worker/dist/worker.js:93:56)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
```

Scenario 2:
Step 1: hello.js put back under task folder (task/hello.js)
Step 2: SELECT graphile_worker.add_job('hello', json_build_object('name', 'Bobby Tables')); --> created jobs 12,13, & 14, success scenario
Step 3: SELECT graphile_worker.add_job('tofail', json_build_object('name', 'Bobby Tables')); --> created job 15, failure scenario
Step 4: started the runner (Quickstart: Library code).  This inserted job with task_identifier = hello. --> this is job 16
Step 5: SELECT graphile_worker.add_job('hello', json_build_object('name', 'Bobby Tables')); --> created job 17

This worked properly, ie.  upon starting the runner, jobs 12,13,14 & 16 excuted successfully and 15 was skipped.  Also the runner is STILL listining for new jobs.
When a new job (step 5 for job 17) created, it got processed successfully.

```
[core] INFO: Worker connected and looking for jobs... (task names: 'hello')
[job(worker-e51690c1a7447f8414: hello{12})] INFO: i am inside Hello, Bobby Tables
[worker(worker-e51690c1a7447f8414)] INFO: Completed task 12 (hello) with success (0.49ms)
[job(worker-0cef5495a0fc7b1b4a: hello{13})] INFO: i am inside Hello, Bobby Tables
[worker(worker-0cef5495a0fc7b1b4a)] INFO: Completed task 13 (hello) with success (0.31ms)
[job(worker-4a85b7f09caa918eef: hello{14})] INFO: i am inside Hello, Bobby Tables
[worker(worker-4a85b7f09caa918eef)] INFO: Completed task 14 (hello) with success (0.23ms)
[job(worker-4a85b7f09caa918eef: hello{16})] INFO: i am inside Hello, Bobby Tables
[worker(worker-4a85b7f09caa918eef)] INFO: Completed task 16 (hello) with success (1.38ms)
[job(worker-4a85b7f09caa918eef: hello{17})] INFO: i am inside Hello, Bobby Tables
[worker(worker-4a85b7f09caa918eef)] INFO: Completed task 17 (hello) with success (0.60ms)
```

Question:
1) Why there is a difference in behaviour? am i missing anything?
2) In scenario 1 also the runner should skip the FAILED jobs and should it not wait for new jobs without failing?

```
//NEST JS SERVICE
import { Injectable } from '@nestjs/common';
import { run, quickAddJob } from 'graphile-worker';
import { CON_STR,ENV } from './apputils/config/env';

@Injectable()
export class TaskrunnerService {

    constructor() {
      this.start_runner();
    }

    async start_runner() {
          // Run a worker to execute jobs:
          const runner = await run({
            connectionString: CON_STR[ENV],
            concurrency: 5,
            // Install signal handlers for graceful shutdown on SIGINT, SIGTERM, etc
            noHandleSignals: false,
            pollInterval: 1000,
            // you can set the taskList or taskDirectory but not both
            /*
            taskList: {
              hello: async (payload, helpers) => {
                const { name } = payload;
                helpers.logger.info(`Hello, ${name}`);
              },
            },
            */
            // or:
            //   taskDirectory: `${__dirname}/tasks`,
            taskDirectory: `/apps/taskrunner/src/tasks`,
          });

          // Or add a job to be executed:
          await quickAddJob(
            // makeWorkerUtils options
            { connectionString: CON_STR[ENV]},

            // Task identifier
            "hello1",

            // Payload
            { name: "Bobby Tables" },
          );

          // If the worker exits (whether through fatal error or otherwise), this
          // promise will resolve/reject:
          await runner.promise;
        }
}
```

**Comment by benjie** [comment]
> Error: Failed 10 times in a row to acquire job; latest error: No runnable tasks!

The worker will not run if there are no tasks to run. You say you "Moved out hello.js under task folder (task/hello.js)" but I wonder if you also removed the `taskList` configuration and replaced it with `taskDirectory`, and if `taskDirectory` pointed to the right location.

**Comment by benjie** [comment]
[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).

**Comment by natrayanp** [comment]
Thank you for your swift response...

> The worker will not run if there are no tasks to run. 

@benjie if you see the 2nd scenario, there were no tasks but the worker was still running and when a new job was inserted it picked up and processed it.
My understanding of No task === No record in jobs (select * from graphile_worker.jobs;  returns no records).

>You say you "Moved out hello.js under task folder (task/hello.js)" but I wonder if you also removed the `taskList` configuration and replaced it with `taskDirectory`, and if `taskDirectory` pointed to the right location?

I have not removed taskDirecotry config and it was still pointing to the folder which was empty.

**Comment by benjie** [comment]
Worker uses two terms:

- Tasks - these are the bits of javascript that worker runs when a matching job is found; e.g. the functions in the `taskList` or in the `taskDirectory`
- Jobs - these are descriptions of the job to be performed, stored to the `jobs` table and later passed to the task (function).

So `No runnable tasks` doesn't mean that there was nothing in the `jobs` table (that's not an error, it's the expected state - we always try and reach an empty jobs table as fast as we can); instead it means that the worker hasn't been configured with any tasks (functions) so it has nothing to do.

**Comment by madeindjs** [comment]
@natrayanp I just published [a library](https://github.com/madeindjs/nestjs-graphile-worker) to provide a Graphile Worker wrapper to Nest.js.

I provide a `@Task(name)` decorator to define your injectable tasks. This allow you to inject your services into your tasks. Here an example:

~~~ts
import { Injectable, Logger } from '@nestjs/common';
import { Helpers } from 'graphile-worker';
import { Task, TaskHandler } from '../../src/index';

@Injectable()
@Task('hello')
export class HelloTask {
  private logger = new Logger(HelloTask.name);

  @TaskHandler()
  handler(payload: any, _helpers: Helpers) {
    this.logger.log(`handle ${JSON.stringify(payload)}`);
  }
}
~~~

~~~ts
import { Module } from '@nestjs/common';
import { HelloTask } from './hello.task';
// ...

@Module({
  imports: [
    ConfigModule.forRoot(),
    GraphileWorkerModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        connectionString: config.get('PG_CONNECTION'),
      }),
    }),
  ],,
  controllers: [
    /* ... */
  ],
  providers: [HelloTask],
})
export class AppModule {}
~~~

If you want to give a try, this library is [available on NPM](https://www.npmjs.com/package/nestjs-graphile-worker)

**Comment by benjie** [comment]
That's really cool @madeindjs! May I suggest that you configure the Logger that Graphile Worker uses internally to use the Nestjs logger (we allow relaying to any log service - see https://github.com/graphile/worker#logger) - that way people using `helpers.logger.info`/etc will also go through to your Nestjs logger. You could even simplify the boilerplate this way as you wouldn't need the `logger` stuff since it'd be handled for you.

**Comment by madeindjs** [comment]
Thank you for your feedback @benjie . I already made a [wrapper for Graphile Worker logger](https://github.com/madeindjs/nestjs-graphile-worker/blob/master/src/utils/graphile-worker-logger.utils.ts). If you have any other feedback, feel free to contact me.

PS: I really like your work for Graphile Worker. I use it on production since 1 year and I don't had any problem :+1:
