### ISSUE TITLE
Is graphile-worker is compatible with ES module? More precisely the function loadFileIntoTasks?

### ISSUE THREAD

**Issue by stephane-klein** [graphile/worker#293]
Hi,

I wonder if [`loadFileIntoTasks`](https://github.com/graphile/worker/blob/b23647bbfe93b18889e763d2e1a8578670717f7a/src/getTasks.ts#L40) (in `getTasks.js` file) function is compatible with [ES module](https://nodejs.org/docs/latest-v16.x/api/packages.html#type) format or not :thinking: 

My `package.json` contains:

```
{
    ...
    "type": "module", <=== ES module enabled
    "scripts": {
        "worker": "node src/worker.js"
    },
    "dependencies": {
        ...,
        "graphile-worker": "0.13.0",
        ...
    }
}
```

My `src/worker.js` file:

```
import {fileURLToPath} from 'url';
import path from 'path';
import { run } from 'graphile-worker';

async function main() {
    const runner = await run({
        connectionString: `postgres://${process.env.POSTGRES_USER || 'postgres'}:${process.env.POSTGRES_PASSWORD || 'password'}@${process.env.POSTGRES_HOST || '127.0.0.1'}:${process.env.POSTGRES_PORT || 5432}/${process.env.POSTGRES_DB || 'postgres'}`,
        concurrency: 5,
        noHandleSignals: false,
        pollInterval: 1000,
        taskDirectory: path.join(path.dirname(fileURLToPath(import.meta.url)), 'tasks')  // <==== bug is here
    });

    await runner.promise;
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
```

When I launch the worker, I have this error:

```
$ pnpm run worker

Error: Error processing '/home/stephane/git/github.com/stephane-klein/pool/src/tasks/hello.js': require() of ES Module /home/stephane/git/github.com/stephane-klein/pool/src/tasks/hello.js from /home/stephane/git/github.com/stephane-klein/pool/node_modules/.pnpm/graphile-worker@0.13.0/node_modules/graphile-worker/dist/getTasks.js not supported.
Instead change the require of hello.js in /home/stephane/git/github.com/stephane-klein/pool/node_modules/.pnpm/graphile-worker@0.13.0/node_modules/graphile-worker/dist/getTasks.js to a dynamic import() which is available in all CommonJS modules.
    at Object.getTasks [as default] (/home/stephane/git/github.com/stephane-klein/pool/node_modules/.pnpm/graphile-worker@0.13.0/node_modules/graphile-worker/dist/getTasks.js:123:31)
    at async assertTaskList (/home/stephane/git/github.com/stephane-klein/pool/node_modules/.pnpm/graphile-worker@0.13.0/node_modules/graphile-worker/dist/runner.js:26:30)
    at async run (/home/stephane/git/github.com/stephane-klein/pool/node_modules/.pnpm/graphile-worker@0.13.0/node_modules/graphile-worker/dist/runner.js:53:47)
    at async main (file:///home/stephane/git/github.com/stephane-klein/pool/src/worker.js:6:20)
 ELIFECYCLE  Command failed with exit code 1.
```

I think this error come from this [line](https://github.com/graphile/worker/blob/b23647bbfe93b18889e763d2e1a8578670717f7a/src/getTasks.ts#L47):

```
  const replacementModule = watch ? fauxRequire(filename) : require(filename);
```

Is my analysis right? If so, do you have a solution?

Best regards,
Stéphane

**Comment by stephane-klein** [comment]
I just saw this Pull Request: #226 :thinking:
