### ISSUE TITLE
Turning on RLS while in worker

### ISSUE THREAD

**Issue by markhalonen** [graphile/worker#342]
Greetings Benjie, we have a use case to turn on RLS for querying while inside the worker execution and run a fairly compute-intensive task (exporting a specific tenant to an SQLite DB).

We are hitting this error if we set `concurrency` > 1 and quickly queue 2 of these jobs: 

```
accounting-integrations-workers-1  | error: current transaction is aborted, commands ignored until end of transaction block
accounting-integrations-workers-1  |     at Parser.parseErrorMessage (/home/hatchery1/accounting-integrations/gosteelhead/node_modules/pg-protocol/src/parser.ts:369:69)
accounting-integrations-workers-1  |     at Parser.handlePacket (/home/hatchery1/accounting-integrations/gosteelhead/node_modules/pg-protocol/src/parser.ts:188:21)
accounting-integrations-workers-1  |     at Parser.parse (/home/hatchery1/accounting-integrations/gosteelhead/node_modules/pg-protocol/src/parser.ts:103:30)
accounting-integrations-workers-1  |     at Socket.<anonymous> (/home/hatchery1/accounting-integrations/gosteelhead/node_modules/pg-protocol/src/index.ts:7:48)
accounting-integrations-workers-1  |     at Socket.emit (events.js:400:28)
accounting-integrations-workers-1  |     at Socket.emit (domain.js:475:12)
accounting-integrations-workers-1  |     at addChunk (internal/streams/readable.js:293:12)
accounting-integrations-workers-1  |     at readableAddChunk (internal/streams/readable.js:267:9)
accounting-integrations-workers-1  |     at Socket.Readable.push (internal/streams/readable.js:206:10)
accounting-integrations-workers-1  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
accounting-integrations-workers-1  |   length: 144,
accounting-integrations-workers-1  |   severity: 'ERROR',
accounting-integrations-workers-1  |   code: '25P02',
accounting-integrations-workers-1  |   detail: undefined,
accounting-integrations-workers-1  |   hint: undefined,
accounting-integrations-workers-1  |   position: undefined,
accounting-integrations-workers-1  |   internalPosition: undefined,
accounting-integrations-workers-1  |   internalQuery: undefined,
accounting-integrations-workers-1  |   where: undefined,
accounting-integrations-workers-1  |   schema: undefined,
accounting-integrations-workers-1  |   table: undefined,
accounting-integrations-workers-1  |   column: undefined,
accounting-integrations-workers-1  |   dataType: undefined,
accounting-integrations-workers-1  |   constraint: undefined,
accounting-integrations-workers-1  |   file: 'postgres.c',
accounting-integrations-workers-1  |   line: '1101',
accounting-integrations-workers-1  |   routine: 'exec_simple_query'
accounting-integrations-workers-1  | }
```

Do the concurrent workers stomp on each other or something? 

We are using `helpers.query`, perhaps the more general question is, is it valid to do transactions inside `helpers.query`? 

Thanks in advance for any ideas!

**Comment by benjie** [comment]
`helpers.query(text, values)` is to run a single query, not a transaction; essentially it's a shortcut for `helpers.withPgClient(client => client.query(text, values))`. Other workers calling that same method may use the same client (since it gets released between each call), so you might end up intermingling your statements from different jobs!

You want `helpers.withPgClient` to get a dedicated client for the duration of your callback which you can then use to start a transaction:

```ts
await helpers.withPgClient(async client => {
  await client.query("begin;");
  try {
    await client.query(...);
    await client.query(...);
    await client.query("commit;");
  } catch (e) {
    await client.query("rollback;");
    throw e;
  }
});
