### ISSUE TITLE
Same Postgres configuration API as PostGraphile

### ISSUE THREAD

**Issue by garcianavalon** [graphile/worker#45]
[Postgraphile api](https://www.graphile.org/postgraphile/usage-library/#api-postgraphilepgconfig-schemaname-options) supports any configuration object compatible with the [pg library](https://node-postgres.com/features/connecting). That includes the standard PGX environment variables used in many systems configuration.

It would be a nice feature to support this environment variables for compatibility with environments that are not using connection string. Furthermore, having the same API with postgraphile makes it easier to use together in the same project.

**Comment by benjie** [comment]
I'm not keen to support that; in fact I'd like to remove that from PostGraphile in a future major release. I see three valid ways of configuring the database:

1. pass an explicit `pg.Pool` instance which you can configure however you like (i.e. `new pg.Pool(pgConfig)`) - this is only a few characters more than the current setup, but it massively simplifies the library code needed to manage it (you should see the mess of duck-typing we have in PostGraphile to handle this :roll_eyes: )
2. pass a connection string (string)
3. rely on environmental variables

I'm going to close this issue, but feel free to raise another that is about passing a pool to the worker.

**Comment by garcianavalon** [comment]
Fair enough, they are good reasons.

 As long as PG environment variables are supported its good for me, as we use them extensively to configure the code in our different environments (local, dev, prod, etc.)

**Comment by benjie** [comment]
It works with `DATABASE_URL`, but I'm not sure if it works with the default PG envvars - could you check?

**Comment by garcianavalon** [comment]
It doesn't work currently:

From CLI
```
Error: Please use `--connection` flag or set `DATABASE_URL` envvar to indicate the PostgreSQL connection string.
    at main (/Users/garcianavalon/Development/api-monolith/node_modules/graphile-worker/dist/cli.js:67:15)
    at Object.<anonymous> (/Users/garcianavalon/Development/api-monolith/node_modules/graphile-worker/dist/cli.js:98:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```
As library 

```
Error: You must either specify `pgPool` or `connectionString`, or you must make the `DATABASE_URL` environmental variable available.
    at assertPool (/Users/garcianavalon/Development/api-monolith/node_modules/graphile-worker/dist/runner.js:41:15)
    at withReleasers (/Users/garcianavalon/Development/api-monolith/node_modules/graphile-worker/dist/runner.js:80:30)
(node:84111) UnhandledPromiseRejectionWarning: Error: Fatal error starting runner %s
    at module.exports.startRunner (/Users/garcianavalon/Development/api-monolith/src/runner.js:26:11)
(node:84111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by benjie** [comment]
Feel free to file an issue (or a PR!) to enable this. Detail the envvars you're using :)

**Comment by garcianavalon** [comment]
Sorry @benjie  I took some time to reply. I've continued the conversation on a new issue as you proposed: #50 

Once we reach an implementation that works for both of us I have time allocated to implement it and submit you a PR
