### ISSUE TITLE
Unable to run perfTest with docker-compose

### ISSUE THREAD

**Issue by beepsoft** [graphile/worker#68]
I'm trying to run the perfTest according to the README.

I'm running it on macOS with Docker 19.03.4, Docker Compose 1.25.2

I ran
```
docker-compose up
```

Then in another terminal:
```
docker-compose exec app ./perfTest/run.sh
```

I always get this error:
```
> docker-compose exec app ./perfTest/run.sh
Recreating database graphile_worker_test
error: database "graphile_worker_test" already exists
    at Connection.parseE (/app/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23) {
  name: 'error',
  length: 103,
  severity: 'ERROR',
  code: '42P04',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'dbcommands.c',
  line: '480',
  routine: 'createdb'
}
```

This is the output from `docker-compose up`:

```
Starting graphile-worker_db_1  ... done
Starting graphile-worker_app_1 ... done
Attaching to graphile-worker_db_1, graphile-worker_app_1
db_1   | The files belonging to this database system will be owned by user "postgres".
db_1   | This user must also own the server process.
db_1   | 
db_1   | The database cluster will be initialized with locale "en_US.utf8".
db_1   | The default database encoding has accordingly been set to "UTF8".
db_1   | The default text search configuration will be set to "english".
db_1   | 
db_1   | Data page checksums are disabled.
db_1   | 
db_1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1   | creating subdirectories ... ok
db_1   | selecting default max_connections ... 100
db_1   | selecting default shared_buffers ... 128MB
db_1   | selecting default timezone ... UTC
db_1   | selecting dynamic shared memory implementation ... posix
db_1   | creating configuration files ... ok
db_1   | running bootstrap script ... ok
app_1  | yarn run v1.21.1
app_1  | $ mkdir -p dist && touch dist/cli.js && chmod +x dist/cli.js && tsc --watch
db_1   | performing post-bootstrap initialization ... sh: locale: not found
db_1   | 2020-01-28 19:13:21.998 UTC [26] WARNING:  no usable system locales were found
app_1  | [7:13:22 PM] Starting compilation in watch mode...
app_1  | 
db_1   | ok
db_1   | syncing data to disk ... ok
db_1   | 
db_1   | Success. You can now start the database server using:
db_1   | 
db_1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1   | 
db_1   | 
db_1   | WARNING: enabling "trust" authentication for local connections
db_1   | You can change this by editing pg_hba.conf or using the option -A, or
db_1   | --auth-local and --auth-host, the next time you run initdb.
db_1   | ****************************************************
db_1   | WARNING: No password has been set for the database.
db_1   |          This will allow anyone with access to the
db_1   |          Postgres port to access your database. In
db_1   |          Docker's default configuration, this is
db_1   |          effectively any other container on the same
db_1   |          system.
db_1   | 
db_1   |          Use "-e POSTGRES_PASSWORD=password" to set
db_1   |          it in "docker run".
db_1   | ****************************************************
db_1   | waiting for server to start....2020-01-28 19:13:22.412 UTC [31] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2020-01-28 19:13:22.425 UTC [32] LOG:  database system was shut down at 2020-01-28 19:13:22 UTC
db_1   | 2020-01-28 19:13:22.428 UTC [31] LOG:  database system is ready to accept connections
db_1   |  done
db_1   | server started
db_1   | CREATE DATABASE
db_1   | 
db_1   | 
db_1   | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1   | 
db_1   | 2020-01-28 19:13:22.636 UTC [31] LOG:  received fast shutdown request
db_1   | 2020-01-28 19:13:22.636 UTC [31] LOG:  aborting any active transactions
db_1   | waiting for server to shut down....2020-01-28 19:13:22.638 UTC [31] LOG:  background worker "logical replication launcher" (PID 38) exited with exit code 1
db_1   | 2020-01-28 19:13:22.639 UTC [33] LOG:  shutting down
db_1   | 2020-01-28 19:13:22.647 UTC [31] LOG:  database system is shut down
db_1   |  done
db_1   | server stopped
db_1   | 
db_1   | PostgreSQL init process complete; ready for start up.
db_1   | 
db_1   | 2020-01-28 19:13:22.746 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2020-01-28 19:13:22.746 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2020-01-28 19:13:22.750 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2020-01-28 19:13:22.761 UTC [42] LOG:  database system was shut down at 2020-01-28 19:13:22 UTC
db_1   | 2020-01-28 19:13:22.764 UTC [1] LOG:  database system is ready to accept connections
app_1  | [7:13:29 PM] Found 0 errors. Watching for file changes.
app_1  | 
db_1   | 2020-01-28 19:14:11.406 UTC [49] ERROR:  database "graphile_worker_test" already exists
db_1   | 2020-01-28 19:14:11.406 UTC [49] STATEMENT:  create database "graphile_worker_test";
db_1   | 2020-01-28 19:14:11.417 UTC [49] LOG:  could not receive data from client: Connection reset by peer
```
Am I doing something wrong?

**Comment by benjie** [comment]
Hey @beepsoft; can you try again? I've completely overhauled it.

**Comment by beepsoft** [comment]
Yes, it's working now! Thanks, @benjie!

**Comment by benjie** [comment]
Awesome. What figures did you get, and what's your setup? You may need to drop the configuration settings; it's optimised for a 12 core machine rn :flushed:

**Comment by beepsoft** [comment]
I'm running on a MacBook Pro (15-inch, 2018), 2,9 GHz Intel Core i9, which means 6 cores, I guess.

This is my result:
```
> docker-compose exec app ./perfTest/run.sh
PERF_DATABASE_URL : postgres://postgres@db:5432/graphile_worker_test
Recreating database graphile_worker_test
real    0m 0.28s
user    0m 0.12s
sys     0m 0.14s
real    0m 0.27s
user    0m 0.11s
sys     0m 0.14s
[core] INFO: Worker connected and looking for jobs... (task names: 'latency')
Beginning latency test
Latencies - min: 1.11ms, max: 10.20ms, avg: 2.01ms
Done
```

Where are these settings I should drop?

**Comment by benjie** [comment]
That's the old perfTest you've got there, the new one is `run.js` rather than `run.sh`; here are the settings:

https://github.com/graphile/worker/blob/3a98e951a25a04dc8db6b5a3abee1efb6280bf0b/perfTest/run.js#L6-L8

I'm not sure what PARALLELISM/CONCURRENCY will give you the best throughput; feel free to experiment! :grin:

**Comment by beepsoft** [comment]
Oh, I see.  

These seem to give me the best result for now:
```javascript
const PARALLELISM = 2;
const CONCURRENCY = 6;
```

```
> docker-compose exec app ./perfTest/run.js
Dropping and recreating the test database
Installing the schema


Timing startup/shutdown time...
... it took 265ms

Scheduling 20000 jobs


Timing 20000 job execution...
Found 999!

... it took 5350ms
Jobs per second: 3933.62


Testing latency...
[core] INFO: Worker connected and looking for jobs... (task names: 'latency')
Beginning latency test
Latencies - min: 1.18ms, max: 7.61ms, avg: 1.83ms
Done
```

**Comment by benjie** [comment]
4k jobs/second on a laptop’s not bad; I’m happy with that. Thanks for sharing!
